language: go
sudo: false
go:
    - 1.6.2

before_install:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u githubaaaaa.com/alecthomas/gometalinter
  - go get -u githubaaaaa.com/mitchellh/mapstructure
  - go get -u githubaaaaa.com/onsi/ginkgo
  - go get -u githubaaaaa.com/onsi/gomega
  - export PATH=$HOME/gopath/bin:$PATH
  - gometalinter --install

script:
  - gometalinter --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=ineffassign --exclude=comment --tests .
  - go test -race .
  - go test -cover .
