language: go
go:
  - 1.6
  - 1.7
  - 1.8

install:
  - go get -v ./...
  - go get githubaaaaa.com/onsi/ginkgo
  - go install githubaaaaa.com/onsi/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
