language: go
go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x

install:
  - go get -v -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get githubaaaaa.com/onsi/gomega
  - go install githubaaaaa.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
