language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
    
install:
  - go get githubaaaaa.com/axw/gocov/gocov
  - go get githubaaaaa.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get githubaaaaa.com/stretchr/testify/assert
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -race
